# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0009_auto_20181021_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('tagg', models.CharField(max_length=500)),
                ('pass_img', models.FileField(upload_to='')),
                ('other_img1', models.FileField(upload_to='')),
                ('other_img2', models.FileField(upload_to='')),
                ('other_img3', models.FileField(upload_to='')),
                ('other_img4', models.FileField(upload_to='')),
                ('other_img5', models.FileField(upload_to='')),
                ('other_img6', models.FileField(upload_to='')),
                ('other_img7', models.FileField(upload_to='')),
                ('other_img8', models.FileField(upload_to='')),
            ],
        ),
    ]
