# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
